default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: notificator
  encoding: unicode
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: notificator_test
  encoding: unicode
  username: postgres
  password: postgres
  host: localhost
  port: 5432